version: '3'
services:

  bd:
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proposta
      MYSQL_PASSWORD: root
    volumes:
      - /home/viniciusferreira/Desktop/projects/ot_microservice/orange-talents-08-template-proposta/proposalmicroservice/volumeDB:/var/lib/mysql
    restart: on-failure

  proposta:
    build:
      dockerfile: Dockerfile
      context: .
    image: zvinicius/proposta
    ports:
      - "8081:8080"
    environment:
      URLBANCO: jdbc:mysql://bd:3306/proposta
      URL_API_ANALISE_FINANCEIRA: http://analise:9999/api/solicitacao
      URL_API_CARTOES: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: on-failure
    depends_on:
      - bd
      - contas
      - analise

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak:11.0.0
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - prometheus
      - jaeger
      - kafka
      - zookeeper
      - contas
      - analise
      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
    restart: on-failure

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  transacoes:
    image: 'zupacademy/transacoes'
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
    #  - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus-volume:/etc/prometheus/
    network_mode: host
    ports:
      - "9090:9090"

volumes:
  prometheus-volume:
  postgres-volume:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24